# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Nane', models.CharField(max_length=200)),
                ('Phone_number1', models.CharField(max_length=200)),
                ('Phone_number2', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
            ],
        ),
    ]
